require("custom-env").env('default');

CONFIG = {};

CONFIG.APP_PORT = process.env.APP_PORT;
CONFIG.DATABASE_URL = process.env.DATABASE_URL;
CONFIG.JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
CONFIG.JWT_EXPIRATION = process.env.JWT_EXPIRATION;
CONFIG.COOKIE_EXPIRATION = process.env.COOKIE_EXPIRATION;
CONFIG.JWT_FORGOT_PASSWORD_KEY = process.env.JWT_FORGOT_PASSWORD_KEY;
CONFIG.JWT_FORGOT_PASSWORD_EXPIRATION = process.env.JWT_FORGOT_PASSWORD_EXPIRATION;
CONFIG.USER_MAIL = process.env.USER_MAIL;
CONFIG.USER_PASSWORD = process.env.USER_PASSWORD;
CONFIG.MAIL_HOST = process.env.MAIL_HOST;
CONFIG.MAIL_PORT = process.env.MAIL_PORT;
CONFIG.AWS_SES_ACCESS_KEY = process.env.AWS_SES_ACCESS_KEY;
CONFIG.AWS_SES_SECRET_KEY = process.env.AWS_SES_SECRET_KEY;
CONFIG.RAZORPAY_KEYID = process.env.RAZORPAY_KEYID;
CONFIG.RAZORPAY_SECRETKEY = process.env.RAZORPAY_SECRETKEY;
CONFIG.RAZORPAY_WEBHOOK_SECRET = process.env.RAZORPAY_WEBHOOK_SECRET;

module.exports = CONFIG;